#!/bin/sh

FIFO="/tmp/dvtm-status.$$"

[ -e "$FIFO" ] || mkfifo "$FIFO"
chmod 600 $FIFO

while true; do
	conky -c ~/.conkyrc-dvtm
	sleep 5
done > $FIFO &

STATUS_PID=$!
/home/ebirtaid/build/dvtm/dvtm-0.5.1/dvtm -s $FIFO 2> /dev/null
kill $STATUS_PID
rm $FIFO
